#!/usr/bin/env bash
# checks for command line arguments

if [ $# -lt 4 ]
then
echo "Usage: 0-transfer_file PATH_TO_FILE_IP USERNAME PATH_TO_SSH_KEY"
exit 1
fi

# assigns parameters to variables

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

#this disables strict host key checking

scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"


# checking if the transfer was successful
if [ $? -eq 0 ]
then
echo "FILE WAS TRANSFERRED SUCCESSFULLY"
else
echo "FILE TRANSFER FAILED"
fi
