#!/usr/bin/env bash
#this customises a 404 page

sudo apt-get update
sudo apt-get install -y nginx

#this creates a 404 page

echo "Ceci n'est pas une page." | sudo tee /var/www/html/404.html

string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html; {\n\troot \/var/www/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart nginx after implementing changes

sudo service nginx restart
